version: "3.8"

services:
  oxidized-roga-challenge-db:
    container_name: mysql
    user: "1000:1000"
    env_file:
      - ../.env
    build:
      context: ./.local
      dockerfile: Dockerfile-MySQL
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PORT: ${DATABASE_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    restart: on-failure:5

  oxidized-roga-redis:
    container_name: redis
    command: bash -c "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    user: "1000:1000"
    build:
      context: ./.local
      dockerfile: Dockerfile-Redis
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
    restart: on-failure:5
